name: Disguise
version: '1.0'
main: org.doraji.disguise.Disguise
api-version: '1.21'
depend: [ NickAPI ]
commands:
  disguise:
    description: 플레이어를 변장 시킬 수 있습니다.
    usage: /disguise <플레이어> <스킨 소유자>
    permission: disguise.use
    permission-message: You don't have permission to use this command.
permissions:
  disguise.use:
    description: 플레이어를 다른 플레이어로 변장할 수 있도록 도와주는 권한입니다.
    default: op
